[terminal.shell]
program="/bin/zsh"

[window]
blur=true
opacity=0.85

[terminal]

[colors.primary]
background="#1c1c1c"

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" }
